name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

  review:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Request Approval
      uses: actions/github-script@v6
      with:
        script: |
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            reviewers: ['pradeepkumarreddypalagiri7@gmail.com']
          });

    - name: Wait for Approval
      uses: actions/github-script@v6
      with:
        script: |
          const { data } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });
          
          if (data.reviews.some(review => review.state === 'APPROVED')) {
            console.log('Approved!');
          } else {
            console.log('Waiting for approval...');
            process.exit(1);
          }

  deploy:
    runs-on: ubuntu-latest
    needs: review

    steps:
    - name: Deploy to Stage/QA/Prod
      run: |
        # Add deployment scripts here
        # e.g., deploying to a staging server
        echo "Deploying to Staging..."
