name: Deploy to Stage

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Stage
      run: |
        # Your deployment script or commands here
        echo "Deploying to Stage..."
      env:
        GITHUB_TOKEN: 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

        name: Approval

on:
  pull_request:
    types:
      - opened

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
    - name: Request Approval
      uses: actions/github-script@v5
      with:
        script: |
          const result = await github.pulls.createReviewRequest({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            reviewers: pradeep-palagiri,
          });
          console.log(result);
        env:
          GITHUB_TOKEN: name: Approval

on:
  pull_request:
    types:
      - opened

jobs:
  approval:
    runs-on: ubuntu-latest

    steps:
    - name: Request Approval
      uses: actions/github-script@v5
      with:
        script: |
          const result = await github.pulls.createReviewRequest({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            reviewers: pradeep-palagiri,
          });
          console.log(result);
        env:
          GITHUB_TOKEN: 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

          name: Deploy to Stage

on:
  workflow_run:
    workflows: ["Approval"]
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Stage
      run: |
        # Your deployment script or commands here
        echo "Deploying to Stage..."
      env:
        GITHUB_TOKEN: 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
